# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55956cc4aa8cb473adf8979d1627edd7a8513b5982a173b977a0892eff1692803aa97db6f611772b6214b9306b203e075681a2eca18c42f11bdbf139170398b7

test:
  secret_key_base: a667abb188a38c33c0693594527bfda2bb409a6ff95a122de7a56c9d91fc25f3e28b1159c24e18f19a70f02205965246b1d4ec232ad72ab1190f1f751a322f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
